filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=build/coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
